/**
 * Migration script to populate vehicle_metadata from website cars.ts data
 * Matches vehicles by license plate, then by brand + model + year + color
 *
 * Run with: npx tsx server/src/scripts/migrateVehicleMetadata.ts
 */

import { pool } from '../db/database.js'

interface WebsiteCar {
  id: string
  brand: string
  model: string
  year: number
  category: string
  pricePerDay: number
  image: string
  images: string[]
  features: string[]
  transmission: string
  fuel: string
  seats: number
  luggage: number
  available: boolean
  rating: number
  reviews: number
  description: string
  color?: string
  licensePlate?: string
  longTermOnly?: boolean
  byRequest?: boolean
  specifications: {
    engine: string
    power: string
    acceleration: string
    topSpeed: string
  }
}

// Website cars data
const websiteCars: WebsiteCar[] = [
  // Premium/Sport
  {
    id: 'mustang-yellow-2021',
    brand: 'Ford',
    model: 'Mustang',
    year: 2021,
    category: 'sport',
    pricePerDay: 15000,
    image: '/images/cars/mustang-yellow-2021/main.jpg',
    images: ['/images/cars/mustang-yellow-2021/1.jpg', '/images/cars/mustang-yellow-2021/2.jpg', '/images/cars/mustang-yellow-2021/3.jpg'],
    features: ['V8 Engine', 'Sport Suspension', 'Brembo Brakes', 'Launch Control'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 4,
    luggage: 2,
    available: true,
    rating: 4.9,
    reviews: 87,
    description: 'Legendary American muscle car with powerful V8 engine. Yellow edition.',
    color: 'Yellow',
    licensePlate: 'UNI0000',
    specifications: { engine: '5.0L V8', power: '450 hp', acceleration: '4.3 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'mustang-yellow-2016',
    brand: 'Ford',
    model: 'Mustang',
    year: 2016,
    category: 'sport',
    pricePerDay: 15000,
    image: '/images/cars/mustang-yellow-2016/main.jpg',
    images: ['/images/cars/mustang-yellow-2016/1.jpg', '/images/cars/mustang-yellow-2016/2.jpg'],
    features: ['V8 Engine', 'Sport Mode', 'Premium Sound', 'Leather Interior'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 4,
    luggage: 2,
    available: true,
    rating: 4.8,
    reviews: 124,
    description: 'Classic Mustang with aggressive styling. Yellow edition.',
    color: 'Yellow',
    licensePlate: 'UNI0001',
    specifications: { engine: '5.0L V8', power: '435 hp', acceleration: '4.5 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'mustang-blue-2020',
    brand: 'Ford',
    model: 'Mustang',
    year: 2020,
    category: 'sport',
    pricePerDay: 15000,
    image: '/images/cars/mustang-blue-2020/main.jpg',
    images: ['/images/cars/mustang-blue-2020/1.jpg', '/images/cars/mustang-blue-2020/2.jpg', '/images/cars/mustang-blue-2020/3.jpg'],
    features: ['V8 Engine', 'Sport Suspension', 'SYNC 3', 'Track Apps'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 4,
    luggage: 2,
    available: true,
    rating: 4.9,
    reviews: 98,
    description: 'Stunning blue Mustang with modern features and classic power.',
    color: 'Blue',
    licensePlate: 'UNI0002',
    specifications: { engine: '5.0L V8', power: '450 hp', acceleration: '4.3 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'mustang-white-2020',
    brand: 'Ford',
    model: 'Mustang',
    year: 2020,
    category: 'sport',
    pricePerDay: 15000,
    image: '/images/cars/mustang-white-2020/main.jpg',
    images: ['/images/cars/mustang-white-2020/1.jpg', '/images/cars/mustang-white-2020/2.jpg'],
    features: ['V8 Engine', 'Premium Package', 'B&O Sound', 'Active Exhaust'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 4,
    luggage: 2,
    available: true,
    rating: 4.9,
    reviews: 76,
    description: 'Elegant white Mustang combining style and performance.',
    color: 'White',
    licensePlate: '1013',
    specifications: { engine: '5.0L V8', power: '450 hp', acceleration: '4.3 sec', topSpeed: '250 km/h' },
  },
  // BMW
  {
    id: 'bmw-430i-black',
    brand: 'BMW',
    model: '430i',
    year: 2020,
    category: 'premium',
    pricePerDay: 15000,
    image: '/images/cars/bmw-430i-black/main.jpg',
    images: ['/images/cars/bmw-430i-black/1.jpg', '/images/cars/bmw-430i-black/2.jpg', '/images/cars/bmw-430i-black/3.jpg'],
    features: ['M Sport Package', 'Adaptive Suspension', 'Head-Up Display', 'Harman Kardon'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 4,
    luggage: 2,
    available: true,
    rating: 4.9,
    reviews: 112,
    description: 'Elegant sports coupe with superior dynamics. Black edition.',
    color: 'Black',
    licensePlate: 'UNI0017',
    specifications: { engine: '2.0L Turbo', power: '258 hp', acceleration: '5.8 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'bmw-430i-orange',
    brand: 'BMW',
    model: '430i',
    year: 2020,
    category: 'premium',
    pricePerDay: 15000,
    image: '/images/cars/bmw-430i-orange/main.jpg',
    images: ['/images/cars/bmw-430i-orange/1.jpg', '/images/cars/bmw-430i-orange/2.jpg'],
    features: ['M Sport Package', 'Laser Lights', 'Premium Sound', 'Sport Seats'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 4,
    luggage: 2,
    available: true,
    rating: 4.8,
    reviews: 89,
    description: 'Head-turning orange BMW coupe with M Sport styling.',
    color: 'Orange',
    licensePlate: 'UNI0018',
    specifications: { engine: '2.0L Turbo', power: '258 hp', acceleration: '5.8 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'bmw-420i-blue',
    brand: 'BMW',
    model: '420i',
    year: 2020,
    category: 'premium',
    pricePerDay: 15000,
    image: '/images/cars/bmw-420i-blue/main.jpg',
    images: ['/images/cars/bmw-420i-blue/1.jpg', '/images/cars/bmw-420i-blue/2.jpg'],
    features: ['M Sport Package', 'Navigation', 'Parking Assistant', 'LED Lights'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 4,
    luggage: 2,
    available: true,
    rating: 4.8,
    reviews: 67,
    description: 'Sleek blue BMW coupe perfect for the island roads.',
    color: 'Blue',
    licensePlate: 'UNI0019',
    specifications: { engine: '2.0L Turbo', power: '184 hp', acceleration: '7.5 sec', topSpeed: '240 km/h' },
  },
  // Mercedes S-Class
  {
    id: 'mercedes-s-class',
    brand: 'Mercedes-Benz',
    model: 'S-Class',
    year: 2020,
    category: 'premium',
    pricePerDay: 15000,
    image: '/images/cars/mercedes-s-class-1.jpg',
    images: ['/images/cars/mercedes-s-class-1.jpg', '/images/cars/mercedes-s-class-2.jpg', '/images/cars/mercedes-s-class-3.jpg', '/images/cars/mercedes-s-class-4.jpg', '/images/cars/mercedes-s-class-5.jpg', '/images/cars/mercedes-s-class-6.jpg', '/images/cars/mercedes-s-class-7.jpg'],
    features: ['Executive Rear Seats', 'Burmester Sound', 'Massage Function', 'Air Suspension'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 5.0,
    reviews: 45,
    description: 'The pinnacle of luxury sedans. Ultimate comfort and prestige.',
    color: 'Black',
    licensePlate: 'UNI0016',
    specifications: { engine: '3.0L Turbo', power: '367 hp', acceleration: '5.1 sec', topSpeed: '250 km/h' },
  },
  // SUVs
  {
    id: 'raptor-2023',
    brand: 'Ford',
    model: 'Raptor',
    year: 2023,
    category: 'suv',
    pricePerDay: 7000,
    image: '/images/cars/raptor-2023/main.jpg',
    images: ['/images/cars/raptor-2023/1.jpg', '/images/cars/raptor-2023/2.jpg', '/images/cars/raptor-2023/3.jpg', '/images/cars/raptor-2023/4.jpg'],
    features: ['FOX Suspension', '4WD', 'Terrain Management', 'Off-Road Mode'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 4,
    available: true,
    rating: 4.9,
    reviews: 134,
    description: 'Extreme pickup for off-road adventures. 2023 model.',
    color: 'Black',
    licensePlate: '4804',
    specifications: { engine: '2.0L Turbo', power: '213 hp', acceleration: '10.5 sec', topSpeed: '170 km/h' },
  },
  {
    id: 'raptor-2024',
    brand: 'Ford',
    model: 'Raptor',
    year: 2024,
    category: 'suv',
    pricePerDay: 7000,
    image: '/images/cars/raptor-2024/main.jpg',
    images: ['/images/cars/raptor-2024/1.jpg', '/images/cars/raptor-2024/2.jpg', '/images/cars/raptor-2024/3.jpg'],
    features: ['FOX Suspension', '4WD', 'Terrain Management', 'Trail Control'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 4,
    available: true,
    rating: 5.0,
    reviews: 56,
    description: 'Latest Raptor model with enhanced off-road capabilities.',
    color: 'Black',
    licensePlate: '4082',
    specifications: { engine: '2.0L Turbo', power: '213 hp', acceleration: '10.5 sec', topSpeed: '170 km/h' },
  },
  {
    id: 'everest-2023',
    brand: 'Ford',
    model: 'Everest',
    year: 2023,
    category: 'suv',
    pricePerDay: 7000,
    image: '/images/cars/everest-2023/main.jpg',
    images: ['/images/cars/everest-2023/1.jpg', '/images/cars/everest-2023/2.jpg', '/images/cars/everest-2023/3.jpg'],
    features: ['7 Seats', 'AWD', 'Hill Descent Control', 'SYNC 4A'],
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 7,
    luggage: 5,
    available: true,
    rating: 4.8,
    reviews: 98,
    description: 'Powerful 7-seater SUV for family adventures.',
    color: 'Black',
    licensePlate: '5793',
    specifications: { engine: '2.0L Turbo Diesel', power: '210 hp', acceleration: '9.8 sec', topSpeed: '180 km/h' },
  },
  {
    id: 'everest-2024',
    brand: 'Ford',
    model: 'Everest',
    year: 2024,
    category: 'suv',
    pricePerDay: 7000,
    image: '/images/cars/everest-2024/main.jpg',
    images: ['/images/cars/everest-2024/1.jpg', '/images/cars/everest-2024/2.jpg'],
    features: ['7 Seats', 'AWD', 'Adaptive Cruise', 'Matrix LED'],
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 7,
    luggage: 5,
    available: true,
    rating: 4.9,
    reviews: 45,
    description: 'Latest Everest with advanced safety features.',
    color: 'Black',
    licensePlate: '7970',
    specifications: { engine: '2.0L Turbo Diesel', power: '210 hp', acceleration: '9.8 sec', topSpeed: '180 km/h' },
  },
  {
    id: 'fortuner',
    brand: 'Toyota',
    model: 'Fortuner',
    year: 2023,
    category: 'suv',
    pricePerDay: 7000,
    image: '/images/cars/fortuner/main.jpg',
    images: ['/images/cars/fortuner/1.jpg', '/images/cars/fortuner/2.jpg', '/images/cars/fortuner/3.jpg'],
    features: ['7 Seats', '4WD', 'Toyota Safety Sense', 'JBL Sound'],
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 7,
    luggage: 4,
    available: true,
    rating: 4.7,
    reviews: 156,
    description: 'Reliable 7-seater SUV perfect for exploring Phuket.',
    color: 'Black',
    licensePlate: 'UNI0008',
    specifications: { engine: '2.8L Diesel', power: '204 hp', acceleration: '10.0 sec', topSpeed: '175 km/h' },
  },
  {
    id: 'c-hr-1',
    brand: 'Toyota',
    model: 'C-HR',
    year: 2020,
    category: 'suv',
    pricePerDay: 1500,
    image: '/images/cars/c-hr/main.jpg',
    images: ['/images/cars/c-hr/1.jpg', '/images/cars/c-hr/2.jpg'],
    features: ['Hybrid Engine', 'Toyota Safety Sense', 'Smart Entry', 'JBL Audio'],
    transmission: 'automatic',
    fuel: 'hybrid',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.6,
    reviews: 89,
    description: 'Stylish hybrid crossover. Long-term rental only.',
    color: 'Black',
    licensePlate: '3180',
    longTermOnly: true,
    specifications: { engine: '1.8L Hybrid', power: '122 hp', acceleration: '11.0 sec', topSpeed: '170 km/h' },
  },
  {
    id: 'c-hr-2',
    brand: 'Toyota',
    model: 'C-HR',
    year: 2020,
    category: 'suv',
    pricePerDay: 1500,
    image: '/images/cars/c-hr/main.jpg',
    images: ['/images/cars/c-hr/1.jpg', '/images/cars/c-hr/2.jpg'],
    features: ['Hybrid Engine', 'Toyota Safety Sense', 'Smart Entry', 'JBL Audio'],
    transmission: 'automatic',
    fuel: 'hybrid',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.6,
    reviews: 67,
    description: 'Stylish hybrid crossover. Long-term rental only.',
    color: 'Black',
    licensePlate: '3455',
    longTermOnly: true,
    specifications: { engine: '1.8L Hybrid', power: '122 hp', acceleration: '11.0 sec', topSpeed: '170 km/h' },
  },
  {
    id: 'mg-zs-blue',
    brand: 'MG',
    model: 'ZS',
    year: 2020,
    category: 'suv',
    pricePerDay: 500,
    image: '/images/cars/mg-zs/main.jpg',
    images: ['/images/cars/mg-zs/1.jpg', '/images/cars/mg-zs/2.jpg'],
    features: ['MG Pilot', '10" Touchscreen', '360° Camera', 'Auto Parking'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 4,
    available: true,
    rating: 4.5,
    reviews: 145,
    description: 'Modern crossover with advanced technology. Long-term only.',
    color: 'Blue',
    licensePlate: '6271',
    longTermOnly: true,
    specifications: { engine: '1.5L', power: '106 hp', acceleration: '11.5 sec', topSpeed: '175 km/h' },
  },
  {
    id: 'mg-zs-black-1',
    brand: 'MG',
    model: 'ZS',
    year: 2020,
    category: 'suv',
    pricePerDay: 500,
    image: '/images/cars/mg-zs/main.jpg',
    images: ['/images/cars/mg-zs/1.jpg', '/images/cars/mg-zs/2.jpg'],
    features: ['MG Pilot', '10" Touchscreen', '360° Camera', 'Auto Parking'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 4,
    available: true,
    rating: 4.5,
    reviews: 98,
    description: 'Modern crossover with advanced technology. Long-term only.',
    color: 'Black',
    licensePlate: '6271-1',
    longTermOnly: true,
    specifications: { engine: '1.5L', power: '106 hp', acceleration: '11.5 sec', topSpeed: '175 km/h' },
  },
  {
    id: 'mg-zs-black-2',
    brand: 'MG',
    model: 'ZS',
    year: 2020,
    category: 'suv',
    pricePerDay: 500,
    image: '/images/cars/mg-zs/main.jpg',
    images: ['/images/cars/mg-zs/1.jpg', '/images/cars/mg-zs/2.jpg'],
    features: ['MG Pilot', '10" Touchscreen', '360° Camera', 'Auto Parking'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 4,
    available: true,
    rating: 4.4,
    reviews: 76,
    description: 'Modern crossover with advanced technology. Long-term only.',
    color: 'Black',
    licensePlate: '2431',
    longTermOnly: true,
    specifications: { engine: '1.5L', power: '106 hp', acceleration: '11.5 sec', topSpeed: '175 km/h' },
  },
  {
    id: 'juke-1',
    brand: 'Nissan',
    model: 'Juke',
    year: 2020,
    category: 'suv',
    pricePerDay: 500,
    image: '/images/cars/juke/main.jpg',
    images: ['/images/cars/juke/1.jpg', '/images/cars/juke/2.jpg'],
    features: ['ProPILOT', 'Bose Sound', 'Around View Monitor', 'Smart Entry'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.5,
    reviews: 87,
    description: 'Compact crossover with unique design. Long-term only.',
    color: 'Black',
    licensePlate: 'UNI0029',
    longTermOnly: true,
    specifications: { engine: '1.0L Turbo', power: '117 hp', acceleration: '10.4 sec', topSpeed: '180 km/h' },
  },
  {
    id: 'juke-2',
    brand: 'Nissan',
    model: 'Juke',
    year: 2020,
    category: 'suv',
    pricePerDay: 500,
    image: '/images/cars/juke/main.jpg',
    images: ['/images/cars/juke/1.jpg', '/images/cars/juke/2.jpg'],
    features: ['ProPILOT', 'Bose Sound', 'Around View Monitor', 'Smart Entry'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.4,
    reviews: 65,
    description: 'Compact crossover with unique design. Long-term only.',
    color: 'Black',
    licensePlate: '9921',
    longTermOnly: true,
    specifications: { engine: '1.0L Turbo', power: '117 hp', acceleration: '10.4 sec', topSpeed: '180 km/h' },
  },
  // Mercedes Sedans
  {
    id: 'mercedes-c300',
    brand: 'Mercedes-Benz',
    model: 'C300',
    year: 2020,
    category: 'premium',
    pricePerDay: 7000,
    image: '/images/cars/mercedes-c300/main.jpg',
    images: ['/images/cars/mercedes-c300/1.jpg', '/images/cars/mercedes-c300/2.jpg', '/images/cars/mercedes-c300/3.jpg'],
    features: ['AMG Line', 'Burmester Sound', 'Digital Cockpit', 'Ambient Lighting'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.8,
    reviews: 134,
    description: 'Sporty luxury sedan with AMG styling.',
    color: 'Black',
    licensePlate: 'UNI0010',
    specifications: { engine: '2.0L Turbo', power: '258 hp', acceleration: '5.9 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'mercedes-c350e-white-1',
    brand: 'Mercedes-Benz',
    model: 'C350e',
    year: 2020,
    category: 'premium',
    pricePerDay: 7000,
    image: '/images/cars/mercedes-c350e-white/main.jpg',
    images: ['/images/cars/mercedes-c350e-white/1.jpg', '/images/cars/mercedes-c350e-white/2.jpg'],
    features: ['Plug-in Hybrid', 'AMG Line', 'Burmester Sound', 'Panoramic Roof'],
    transmission: 'automatic',
    fuel: 'hybrid',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.8,
    reviews: 98,
    description: 'Luxury plug-in hybrid sedan. Eco-friendly performance.',
    color: 'White',
    licensePlate: '7909',
    specifications: { engine: '2.0L Hybrid', power: '320 hp', acceleration: '5.9 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'mercedes-c350e-white-2',
    brand: 'Mercedes-Benz',
    model: 'C350e',
    year: 2020,
    category: 'premium',
    pricePerDay: 7000,
    image: '/images/cars/mercedes-c350e-white/main.jpg',
    images: ['/images/cars/mercedes-c350e-white/1.jpg', '/images/cars/mercedes-c350e-white/2.jpg'],
    features: ['Plug-in Hybrid', 'AMG Line', 'Burmester Sound', 'Panoramic Roof'],
    transmission: 'automatic',
    fuel: 'hybrid',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.7,
    reviews: 87,
    description: 'Luxury plug-in hybrid sedan. Eco-friendly performance.',
    color: 'White',
    licensePlate: '7803',
    specifications: { engine: '2.0L Hybrid', power: '320 hp', acceleration: '5.9 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'mercedes-c350e-white-3',
    brand: 'Mercedes-Benz',
    model: 'C350e',
    year: 2020,
    category: 'premium',
    pricePerDay: 7000,
    image: '/images/cars/mercedes-c350e-white/main.jpg',
    images: ['/images/cars/mercedes-c350e-white/1.jpg', '/images/cars/mercedes-c350e-white/2.jpg'],
    features: ['Plug-in Hybrid', 'AMG Line', 'Burmester Sound', 'Panoramic Roof'],
    transmission: 'automatic',
    fuel: 'hybrid',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.8,
    reviews: 76,
    description: 'Luxury plug-in hybrid sedan. Eco-friendly performance.',
    color: 'White',
    licensePlate: '7937',
    specifications: { engine: '2.0L Hybrid', power: '320 hp', acceleration: '5.9 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'mercedes-c350e-white-4',
    brand: 'Mercedes-Benz',
    model: 'C350e',
    year: 2020,
    category: 'premium',
    pricePerDay: 7000,
    image: '/images/cars/mercedes-c350e-white/main.jpg',
    images: ['/images/cars/mercedes-c350e-white/1.jpg', '/images/cars/mercedes-c350e-white/2.jpg'],
    features: ['Plug-in Hybrid', 'AMG Line', 'Burmester Sound', 'Panoramic Roof'],
    transmission: 'automatic',
    fuel: 'hybrid',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.7,
    reviews: 65,
    description: 'Luxury plug-in hybrid sedan. Eco-friendly performance.',
    color: 'White',
    licensePlate: '7729',
    specifications: { engine: '2.0L Hybrid', power: '320 hp', acceleration: '5.9 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'mercedes-c350e-black',
    brand: 'Mercedes-Benz',
    model: 'C350e',
    year: 2020,
    category: 'premium',
    pricePerDay: 7000,
    image: '/images/cars/mercedes-c350e-black/main.jpg',
    images: ['/images/cars/mercedes-c350e-black/1.jpg', '/images/cars/mercedes-c350e-black/2.jpg'],
    features: ['Plug-in Hybrid', 'AMG Line', 'Burmester Sound', 'Night Package'],
    transmission: 'automatic',
    fuel: 'hybrid',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.9,
    reviews: 54,
    description: 'Luxury plug-in hybrid sedan in striking black.',
    color: 'Black',
    licensePlate: 'UNI0013',
    specifications: { engine: '2.0L Hybrid', power: '320 hp', acceleration: '5.9 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'mercedes-e350',
    brand: 'Mercedes-Benz',
    model: 'E350',
    year: 2020,
    category: 'premium',
    pricePerDay: 7000,
    image: '/images/cars/mercedes-e350/main.jpg',
    images: ['/images/cars/mercedes-e350/1.jpg', '/images/cars/mercedes-e350/2.jpg', '/images/cars/mercedes-e350/3.jpg'],
    features: ['AMG Line', 'Burmester 3D Sound', 'Air Body Control', 'Multibeam LED'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.9,
    reviews: 89,
    description: 'Executive sedan with cutting-edge technology.',
    color: 'Black',
    licensePlate: 'UNI0014',
    specifications: { engine: '2.0L Turbo', power: '299 hp', acceleration: '5.9 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'mercedes-e-class-green',
    brand: 'Mercedes-Benz',
    model: 'E-Class',
    year: 2020,
    category: 'premium',
    pricePerDay: 7000,
    image: '/images/cars/mercedes-e-class-green/main.jpg',
    images: ['/images/cars/mercedes-e-class-green/1.jpg', '/images/cars/mercedes-e-class-green/2.jpg'],
    features: ['AMG Line', 'Burmester Sound', 'MBUX', 'Energizing Package'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.8,
    reviews: 67,
    description: 'Elegant E-Class in unique emerald green.',
    color: 'Green',
    licensePlate: 'UNI0015',
    specifications: { engine: '2.0L Turbo', power: '258 hp', acceleration: '6.2 sec', topSpeed: '250 km/h' },
  },
  {
    id: 'mercedes-vito-maybach',
    brand: 'Mercedes-Benz',
    model: 'Vito Maybach',
    year: 2020,
    category: 'premium',
    pricePerDay: 0,
    image: '/images/cars/vito-maybach/main.jpg',
    images: ['/images/cars/vito-maybach/1.jpg', '/images/cars/vito-maybach/2.jpg', '/images/cars/vito-maybach/3.jpg', '/images/cars/vito-maybach/4.jpg'],
    features: ['VIP Interior', 'Massage Seats', 'Privacy Glass', 'Mini Bar'],
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 7,
    luggage: 4,
    available: true,
    rating: 5.0,
    reviews: 23,
    description: 'Ultimate luxury VIP van. Price on request.',
    color: 'Black',
    licensePlate: 'UNI0032',
    byRequest: true,
    specifications: { engine: '2.0L Diesel', power: '190 hp', acceleration: '9.5 sec', topSpeed: '200 km/h' },
  },
  // Economy
  {
    id: 'honda-jazz',
    brand: 'Honda',
    model: 'Jazz',
    year: 2020,
    category: 'economy',
    pricePerDay: 500,
    image: '/images/cars/honda-jazz/main.jpg',
    images: ['/images/cars/honda-jazz/1.jpg', '/images/cars/honda-jazz/2.jpg'],
    features: ['Honda SENSING', 'Magic Seats', 'Touchscreen', 'Fuel Efficient'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 3,
    available: true,
    rating: 4.5,
    reviews: 112,
    description: 'Practical and fuel-efficient. Long-term rental only.',
    color: 'Black',
    licensePlate: 'UNI0030',
    longTermOnly: true,
    specifications: { engine: '1.5L', power: '121 hp', acceleration: '9.4 sec', topSpeed: '190 km/h' },
  },
  {
    id: 'mazda-2-1',
    brand: 'Mazda',
    model: '2',
    year: 2020,
    category: 'economy',
    pricePerDay: 500,
    image: '/images/cars/mazda-2/main.jpg',
    images: ['/images/cars/mazda-2/1.jpg', '/images/cars/mazda-2/2.jpg'],
    features: ['Skyactiv Technology', 'MZD Connect', 'LED Lights', 'Fuel Efficient'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 2,
    available: true,
    rating: 4.4,
    reviews: 89,
    description: 'Compact and fun to drive. Long-term rental only.',
    color: 'Black',
    licensePlate: '7457',
    longTermOnly: true,
    specifications: { engine: '1.3L', power: '92 hp', acceleration: '10.4 sec', topSpeed: '175 km/h' },
  },
  {
    id: 'mazda-2-2',
    brand: 'Mazda',
    model: '2',
    year: 2020,
    category: 'economy',
    pricePerDay: 500,
    image: '/images/cars/mazda-2/main.jpg',
    images: ['/images/cars/mazda-2/1.jpg', '/images/cars/mazda-2/2.jpg'],
    features: ['Skyactiv Technology', 'MZD Connect', 'LED Lights', 'Fuel Efficient'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 2,
    available: true,
    rating: 4.3,
    reviews: 76,
    description: 'Compact and fun to drive. Long-term rental only.',
    color: 'Black',
    licensePlate: '8299',
    longTermOnly: true,
    specifications: { engine: '1.3L', power: '92 hp', acceleration: '10.4 sec', topSpeed: '175 km/h' },
  },
  {
    id: 'mirage',
    brand: 'Mitsubishi',
    model: 'Mirage',
    year: 2020,
    category: 'economy',
    pricePerDay: 500,
    image: '/images/cars/mirage/main.jpg',
    images: ['/images/cars/mirage/1.jpg', '/images/cars/mirage/2.jpg'],
    features: ['Fuel Efficient', 'Compact Size', 'Easy Parking', 'Air Conditioning'],
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    luggage: 2,
    available: true,
    rating: 4.2,
    reviews: 98,
    description: 'Most economical choice. Long-term rental only.',
    color: 'Black',
    licensePlate: '3314',
    longTermOnly: true,
    specifications: { engine: '1.2L', power: '78 hp', acceleration: '12.0 sec', topSpeed: '165 km/h' },
  },
]

async function migrate() {
  const client = await pool.connect()

  try {
    console.log('Starting vehicle metadata migration...')
    console.log(`Processing ${websiteCars.length} cars from website data\n`)

    let matched = 0
    let unmatched = 0
    let created = 0
    let skipped = 0

    for (const car of websiteCars) {
      // Try to match by license plate first
      let vehicleResult = await client.query(
        'SELECT id, brand, model, year, color FROM vehicles WHERE license_plate = $1',
        [car.licensePlate]
      )

      // If not found, try matching by brand + model + year + color
      if (vehicleResult.rows.length === 0 && car.color) {
        vehicleResult = await client.query(
          `SELECT id, brand, model, year, color FROM vehicles
           WHERE LOWER(brand) = LOWER($1)
             AND LOWER(model) = LOWER($2)
             AND year = $3
             AND LOWER(color) = LOWER($4)
           LIMIT 1`,
          [car.brand, car.model, car.year, car.color]
        )
      }

      if (vehicleResult.rows.length === 0) {
        console.log(`⚠️  No match: ${car.brand} ${car.model} ${car.year} (${car.licensePlate || 'no plate'})`)
        unmatched++
        continue
      }

      const vehicle = vehicleResult.rows[0]
      matched++

      // Check if metadata already exists
      const existingMetadata = await client.query(
        'SELECT id FROM vehicle_metadata WHERE vehicle_id = $1',
        [vehicle.id]
      )

      if (existingMetadata.rows.length > 0) {
        console.log(`⏭️  Skipped (exists): ${car.brand} ${car.model} → vehicle #${vehicle.id}`)
        skipped++
        continue
      }

      // Create metadata
      await client.query(`
        INSERT INTO vehicle_metadata (
          vehicle_id, website_id, category, images, features, specifications,
          seats, luggage, rating, reviews, description, transmission,
          is_visible, display_order, price_by_request, long_term_only
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
      `, [
        vehicle.id,
        car.id,
        car.category,
        car.images,
        car.features,
        JSON.stringify(car.specifications),
        car.seats,
        car.luggage,
        car.rating,
        car.reviews,
        car.description,
        car.transmission,
        true,
        0,
        car.byRequest || false,
        car.longTermOnly || false
      ])

      console.log(`✅ Created: ${car.brand} ${car.model} → vehicle #${vehicle.id} (${car.id})`)
      created++
    }

    console.log('\n--- Migration Summary ---')
    console.log(`Total cars processed: ${websiteCars.length}`)
    console.log(`Matched to vehicles: ${matched}`)
    console.log(`Metadata created: ${created}`)
    console.log(`Skipped (already exists): ${skipped}`)
    console.log(`Unmatched: ${unmatched}`)

    if (unmatched > 0) {
      console.log('\n💡 Tip: Unmatched cars need to be added to the vehicles table first.')
    }

  } catch (error) {
    console.error('Migration error:', error)
    throw error
  } finally {
    client.release()
    await pool.end()
  }
}

migrate().catch(console.error)
